### ISSUE TITLE
Error sorting imports: SyntaxError: Unexpected token, expected; (1:8)

### ISSUE THREAD

**Issue by strongui** [amatiasq/vsc-sort-imports#13]
My line one is this:

`declare const jQuery: JQuery;`

This is in a typescript file.

**Comment by amatiasq** [comment]
Do you have any settings in your VS Code configuration or in the `package.json`?

**Comment by strongui** [comment]
@amatiasq No to both. Do I need to put something to get rid of the error?

**Comment by amatiasq** [comment]
No, in theory if you have no specific configuration it should load the typescript parser.

You can try to manually set the parser to typescript in your `package.json`, [here](https://github.com/amatiasq/vsc-sort-imports#use-a-different-style-or-parser) you have an example.

I guess your extension is `.ts`, right?

**Comment by strongui** [comment]
@amatiasq yes  my files have .ts extension.

I added this to my package.json

```
"importSort": {
  ".js, .jsx, .es6, .es": {
    "parser": "babylon",
    "style": "eslint"
  },
  ".ts, .tsx": {
    "parser": "typescript",
    "style": "eslint"
  }
}
```

Then I restarted VS Code and now it works. Thanks. Maybe it's just some VS Code weirdness? Anyway, ticket can be closed as far as I'm concerned.

**Comment by amatiasq** [comment]
This is weird, it should work out of the box. All you did was to copy what is supposed to be the default configuration. I'll take a deeper look into that.

**Comment by strongui** [comment]
@amatiasq well your fix worked for me :) that you for the quick response! Love the plugin! Not sure, if I can send you any log files if you want? Let me know if I can help.

**Comment by amatiasq** [comment]
Closed by mistake

**Comment by amatiasq** [comment]
Closed due to lack of activity
