### ISSUE TITLE
.vue SFC support

### ISSUE THREAD

**Issue by rndmerle** [amatiasq/vsc-sort-imports#17]
Hi.

import-sort is handling VueJS SFC quite well actually, as you can see here : https://github.com/renke/import-sort/issues/52

So I thought I'll give a try to the VSCode extension.
With .importsortrc config:
```
{
    ".vue, .ts": {
      "parser": "typescript",
      "style": "module"
    }
}
```
I edited your **package.json** to add `"onLanguage:vue"` but the command still does nothing on a .vue file. No error showing in the console.

Any idea ? :)
Thanks for your time.

**Comment by Airkro** [comment]
in settings.json
```json
"sort-imports.languages": [
  "javascript",
  "vue"
]
```

get `Error sorting imports: SyntaxError: Unexpected token`

**Comment by rndmerle** [comment]
Thanks :)
No clue why I didn't see it before.
