### ISSUE TITLE
The imports are not sorted correctly

### ISSUE THREAD

**Issue by ankurarora** [amatiasq/vsc-sort-imports#20]
Hi,

I have flow at top with JSX classes and styles imported. When I save my file this is what I am getting.

**Before Sort**
```
// @flow
import Reboot from 'material-ui/Reboot';
import React from 'react';

import keenImage from '../assets/images/logo.png';

// import sass styles
import '../css/main.scss';

import Footer from '../components/footer/Footer';
import Header from '../components/header/Header';
```

**After Sort Applied**
```
// import sass styles
import '../css/main.scss';

// @flow
import Reboot from 'material-ui/Reboot';
import React from 'react';

import keenImage from '../assets/images/logo.png';
import Footer from '../components/footer/Footer';
import Header from '../components/header/Header';
```

// @flow has been pushed down, I see that as a problem

**Comment by amatiasq** [comment]
I see now. That's actually an intended feature. A comment above a import declaration is considered a comment related to that import so it is moved with the import it's supposed to be related to. I thought you meant the extension was moving the `//@flow` comments below all import declarations, now I see it's not the case.

In any case I understand this can be annoying but this should happen only once per file, right? if you move it back to the top again it won't move it back down, right?

We can try to add an exception for a comment matching exactly `// @flow` but exceptions is not something we want to go with and comes with it's own issues.

What do you think?

**Comment by ankurarora** [comment]
Instead of looking at // @flow, how about disabling a line to move if it has some special comment for e.g. // @flow ignore-sort-imports? Using this it will give an option to stop moving lines which has that comment at end of line

**Comment by cliffkoh** [comment]
Hi @ankurarora, I strongly recommend just leaving a blank line between `// @flow` and the first import statement. 
This will fix the problem entirely while allowing you to use the extension. Let me know if there are some reasons you're strongly opposed to doing this though...

**Comment by callumlocke** [comment]
I think it would be good for this VSCode plugin to support it automatically.

This plugin is great, but its basic purpose is to provide a shortcut for a repetitive task. It should 'just work' in as many cases as possible, otherwise I might as well go back to manually sorting imports. It's a handy, niche editor plugin at the end of the day, and Flow is a major, widespread tool. The suggestion that Flow users should introduce and remember new code style rules for compatibility with this plugin is a non-starter in my opinion. The problem here is that vsc-sort-imports mangles a widely used tooling directive (`// @flow`).

**Comment by callumlocke** [comment]
If ignoring them means never moving comment lines from the top, that's fine with me.

**Comment by ankurarora** [comment]
with "ignoring" I meant specifically  the comments from the top i.e. before first import

**Comment by cliffkoh** [comment]
The counterargument for the current behavior is that folks sometime want to document an import. Scenarios might include documenting why something that is not directly referenced is being imported. Ignoring all top-of-file comments will break other people in this scenario.

However, as a compromise, one thing we can do is allow this to be a user preference setting. If a workspace uses flow extensively and does not care for preserving comments on import statements, we can skip the first `n` lines where `n` = number of lines of comments at the top of the file. 

Contributions welcome ^_^

**Comment by amatiasq** [comment]
@wootwoot1234 Thanks for the appreciation, keep in mind that @peterjuras made most of this project from start :)

Reviews are what they are, everyone is free to evaluate as they feel but thank you so much for the effort 👍

**Comment by amatiasq** [comment]
Closed since solutions have been provided and discussion is over.
