### ISSUE TITLE
Error sorting imports: TypeError: style is not a function

### ISSUE THREAD

**Issue by stormwarning** [amatiasq/vsc-sort-imports#22]
I get the above error when running `Sort imports` in VS Code. 

I have the following in my `package.json`

```json
  "importSort": {
    ".js": {
      "parser": "babylon",
      "style": "ember"
    }
  }
```

I have `import-sort` and the custom sort style installed globally, rather than in the project dependencies, however it works as expected when running the CLI version so it seems like it should work with the editor plugin too.

**Comment by amatiasq** [comment]
The custom style should be installed locally, the CLI version works because it's installed globally but the one used by the editor plugin is not.

I'd keep this issue open to improve the error message though.

**Comment by stormwarning** [comment]
Ah that makes sense. Is it possible to have the plugin check for a global install if it's not found locally, or would that be an "upstream" issue? I had a look through the code but I couldn't quite suss out where I'd make that change if I was going to submit a PR.

**Comment by jgomesmv** [comment]
I'm also facing this issue when saving files. Is this error provoked by a bad configuration or something else?
I have just installed the extension on my vs code and set this configs on my package.json:
  "importSort": {
    ".js, .jsx, .es6, .es": {
      "parser": "babylon",
      "style": "eslint",
      "options": {}
    },
    ".ts, .tsx": {
      "parser": "typescript",
      "style": "tslint",
      "options": {}
    }
  },

**Comment by amatiasq** [comment]
@jgomesmv Without a deeper look I think this is related to the new version of `import-sort`, I need to check that when I have time. Can you please create an issue for your problem in particular?

**Comment by jgomesmv** [comment]
After some digging we have fixed the problem. 
You need to change your ts style from tslint to eslint. Just like:
![image](https://user-images.githubusercontent.com/8100887/53633056-55e83200-3c0e-11e9-9af3-ab0bc5878504.png)

**Comment by amatiasq** [comment]
Good catch, I didn't see that
