### ISSUE TITLE
Split/Order by Source

### ISSUE THREAD

**Issue by Undistraction** [amatiasq/vsc-sort-imports#24]
I think a setting to split imports by source would be useful - so that package imports come first, followed by local imports:

```
import Img from 'gatsby-image';
import PropTypes from 'prop-types';
import React from 'react';

import HTMLText from '../../components/shared/HTMLText';
import Metadata from '../../components/Metadata';
import Page from '../../components/Page';
```

**Comment by amatiasq** [comment]
Hy there! You can decide how do you want your imports to be sorted using a different style as explained in the [README](https://github.com/amatiasq/vsc-sort-imports#use-a-different-style-or-parser).

For backward compatibility the default sort type is "eslint" but you probably want [module](https://github.com/renke/import-sort/tree/master/packages/import-sort-style-module) or [module-compact](https://github.com/amatiasq/import-sort-style-module-compact).
