### ISSUE TITLE
sort imports removes flow type imports

### ISSUE THREAD

**Issue by macrozone** [amatiasq/vsc-sort-imports#25]
I have this piece of code:

```
/* @flow */
import { combineReducers } from 'redux'
import tracking, { type TrackingState } from './tracking'

```

after saving, sort-imports removes the type import like this:
```
/* @flow */
import { combineReducers } from 'redux'
import tracking, { TrackingState } from './tracking'

```

**Comment by amatiasq** [comment]
I wasn't aware of this flow special imports, totally blew my mind. I don't know how the parser is not plainly crashing for unexpected syntax.

This extension supports [different parsers](https://github.com/amatiasq/vsc-sort-imports#use-a-different-style-or-parser), we use it for typescript support. I don't have much time to research now but probably there is a parser that knows how to handle this.

This would be simple addition, PRs are always welcome.

**Comment by grahamperich** [comment]
proper solution is to port the flow parser to this extension. the quick work around (which I'm using in my projects) is to import types like so:

`import tracking, type { TrackingState } from './tracking'`

**Comment by grahamperich** [comment]
a workaround would be:

`import type { TrackingState } from './tracking'`
`import tracking from './tracking'`

or just consolidate all of your app's types in a single `types.js` file

**Comment by amatiasq** [comment]
Solution has been provided, closed due to inactivity
