### ISSUE TITLE
Fails with React fragment syntax

### ISSUE THREAD

**Issue by jbox5** [amatiasq/vsc-sort-imports#26]
Plugin seems to fail on files that also contain the new React fragment syntax:
```javascript
<>
  <FindCustomer />
  {hasSearched && <CustomerTable />}
</>
```
Error message:
Error sorting imports: SyntaxError: Unexpected token

**Comment by amatiasq** [comment]
Hi, I will try this when I find a moment and post here what I find.

**Comment by amatiasq** [comment]
@jbox5 A new version of `sort-imports@6.0.0` has been released. It will solve this issue.

Basically our dependencies did not support this feature so we have to upgrade.

**Comment by jbox5** [comment]
Good news, thanks for the update.
