### ISSUE TITLE
Use the sort order in .eslintrc or allow setting of eslint rules

### ISSUE THREAD

**Issue by stevensacks** [amatiasq/vsc-sort-imports#29]
This is my .eslintrc for sorting

```json
        "sort-imports": [
            "warn",
            {
                "ignoreCase": true,
                "memberSyntaxSortOrder": ["multiple", "single", "all", "none"]
            }
        ],
```

It's different than the default, which is `["none", "all", "multiple", "single"]`.

I suggest either reading from eslintrc (or an option to do so), or add the following additional settings:

```
sort-imports.eslint.ignoreCase: true/false
sort-imports.eslint.ignoreMemberSort: true/false
sort-imports.eslint.memberSyntaxSortOrder: // see above for the 4 choices
```

If `sort-imports.default-sort-style` is not eslint, you can ignore those extra settings.

Thoughts?

**Comment by amatiasq** [comment]
I agree this would be an awesome feature, it will be quite complex to implement dough and I don't have much time for it, but if you find time PRs are always welcome.

I guess the way to implement it would be to create a [import-sort style](https://github.com/renke/import-sort/blob/master/packages/import-sort-style-module/src/index.ts) that generates different configurations by reading the `.eslintrc` file.

**Comment by drackp2m** [comment]
I have the same problem as @stevensacks. Unfortunately more than two years have passed and the issue is still open and the feature was not added to the plugin. The truth is that it is a shame, because it is the best of all the ones I found.

I checked the code a little bit above, and I don't dare to touch anything.

**Comment by drackp2m** [comment]
That's fine, knowing that it's not going to get better on its own, maybe when I also have fewer things to do I'll review it more in depth and ask you some questions to try not to break anything, and then do a PR. =)

**Comment by daidodo** [comment]
Sorry to hijack but just walk by and can't help to share that [this extension](https://marketplace.visualstudio.com/items?itemName=dozerg.tsimportsorter) is doing exactly what you ask for. (@drackp2m)
https://github.com/daidodo/format-imports/wiki/ESLint-Compatibility#sort-imports

**Comment by stevensacks** [comment]
I have long since abandoned this for `simple-import-sort`
