### ISSUE TITLE
Keep code folding on after imports sort

### ISSUE THREAD

**Issue by sergeyzwezdin** [amatiasq/vsc-sort-imports#32]
I use `sort-imports` extension and run it on each file save. It's convenient, but I have a problem with large files. When I save the file, the folds expand and the current file position changes.

After googling I came across [this post](https://stackoverflow.com/questions/47325602/how-to-keep-code-folding-on-save-in-visual-studio-code) and found that the reason is your extension.

Could you please make it possible not to expand folded regions?

**Comment by amatiasq** [comment]
This is related to the fact the whole file gets processed when the sorting operation is executed as stated in #7.

This bug has proven really hard to fix, any help will be much appreciated.
