### ISSUE TITLE
Import is moved away in the middle of typing

### ISSUE THREAD

**Issue by RandomEngy** [amatiasq/vsc-sort-imports#35]
I'm in the middle of typing an import and it gets moved away somewhere else. But the cursor is still at the old location. It's really irritating.

**Comment by amatiasq** [comment]
I haven't seen this issue, can you provide a how to reproduce?

**Comment by RandomEngy** [comment]
Ahh somehow the "auto save" functionality got turned on. I guess you can't use that with this extension.

**Comment by amatiasq** [comment]
You can if you disable `sort-imports.on-save` option. Having both at the same time has this natural consequence since the extension is editing the document as you write.
