### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by gagpmr** [amatiasq/vsc-sort-imports#36]
- Issue Type: `Performance`
- Extension Name: `sort-imports`
- Extension Version: `6.0.1`
- OS Version: `Linux x64 4.18.7-041807-generic`
- VSCode version: `1.30.2`

Error file from visual studio code is:-
[amatiasq.sort-imports-unresponsive.cpuprofile.txt](https://github.com/amatiasq/vsc-sort-imports/files/2847781/amatiasq.sort-imports-unresponsive.cpuprofile.txt)

**Comment by amatiasq** [comment]
Hi @gagpmr  looks like you created this issue with some tool that asked you to include a file that is not attached, can you please upload that file?

**Comment by gagpmr** [comment]
Error file from visual studio code is:-
[amatiasq.sort-imports-unresponsive.cpuprofile.txt](https://github.com/amatiasq/vsc-sort-imports/files/2847781/amatiasq.sort-imports-unresponsive.cpuprofile.txt)

**Comment by amatiasq** [comment]
Is this still an issue?

**Comment by amatiasq** [comment]
Closed due to inactivity
