### ISSUE TITLE
import-sort v6

### ISSUE THREAD

**Issue by renke** [amatiasq/vsc-sort-imports#37]
Hi @amatiasq 

I just released v6 of import-sort. There shouldn't be any breaking change API-wise but I am not entirely sure (hence the major version bump). 

`import-sort-parser-typescript` is kind of deprecated in the sense that I won't develop it any further (it doesn't support the new  `// import-sort-ignore` feature, for instance). 

The reason being that `import-sort-parser-babylon` now supports TypeScript as well, so it should in theory do everything that `import-sort-parser-typescript` does.

Best,
Renke

**Comment by amatiasq** [comment]
Thank you @renke, this was updated in #45 thanks to @jquense 👍
