### ISSUE TITLE
sort-imports.firstModules, sort-imports.lastModules

### ISSUE THREAD

**Issue by Yzrsah** [amatiasq/vsc-sort-imports#39]
Feature

```
    "sort-imports.firstModules": [ "react" ],
    "sort-imports.lastModules": [ "@yzrsahs-libs", "a-local-module" ],
```

**Comment by amatiasq** [comment]
Good idea! I think you should create an issue in https://github.com/renke/import-sort, this is the tool we use to do the sorting actually, if you do please reference this issue to track it :)

**Comment by amatiasq** [comment]
Closing since this can't be implemented in this project.
