### ISSUE TITLE
Imports still not sorting correctly

### ISSUE THREAD

**Issue by wbhob** [amatiasq/vsc-sort-imports#4]
I am getting the issue, that if I import from a submodule, it won't sort by packages, demonstrated below. You'll notice that there are imports from @nestjs/core both above and below the break between package and relative imports.
<img width="630" alt="screen shot 2017-10-27 at 7 36 27 pm" src="https://user-images.githubusercontent.com/4442130/32128717-4de185e4-bb4e-11e7-9595-66b41a6b9437.png">

**Comment by wbhob** [comment]
Upon closer look, it seems that they are sorting by quantity, then alphabetically by import name. I'd like to request a feature that it sorts alphabetically by package/path, then by quantity and import name.

**Comment by amatiasq** [comment]
Hi @wbhob, yes I have the same issue with scoped modules (`@`).

I just need a little explanation on what do you mean by "sorting by quantity".

I've wanted to implement that for some time now but had no time for it. A PR would be welcome.

In any case if it's implemented it won't be possible to do it in the default style `eslint` because then the eslint rule is going to notify it as an error.

**Comment by wbhob** [comment]
Yes, so by "quantity", I mean that the packages with more imports come first: notice the first has 9 imports, the second has 2, and the rest have 1.

```ts
import { CanActivate, ExceptionFilter, INestMicroservice, Logger, NestInterceptor, OnModuleDestroy, PipeTransform, WebSocketAdapter } from '@nestjs/core';
import { isNil, isUndefined } from '@nestjs/core/utils/shared.utils';

import { ApplicationConfig } from '@nestjs/core/application-config';
import { CustomTransportStrategy } from './interfaces/custom-transport-strategy.interface';
import { MicroserviceConfiguration } from './interfaces/microservice-configuration.interface';
import { MicroservicesModule } from './microservices-module';
import { Module } from '@nestjs/core/injector/module';
import { NestContainer } from '@nestjs/core/injector/container';
import { Server } from './server/server';
import { ServerFactory } from './server/server-factory';
import { SocketModule } from '@nestjs/websockets/socket-module';
import { Transport } from './enums/transport.enum';
import iterate from 'iterare';
import { messages } from '@nestjs/core/constants';
```

**Comment by amatiasq** [comment]
This is weird, the default sorting style is [import-sort-style-eslint](https://github.com/renke/import-sort/tree/master/packages/import-sort-style-eslint), I don't agree with this style but looks like it's the most popular. It sorts by imported names.

It is made to fulfill [this ESLint rule](https://eslint.org/docs/rules/sort-imports) so you can see here how it works. As you see looks like it's separating imports with multiple identifiers and imports with single identifier and then it's sorting each group alphabetically (uppercase first).

You can switch to a different sorting style by adding [this](https://github.com/amatiasq/vsc-sort-imports#use-a-different-style-or-parser) to you package.json.

**Comment by amatiasq** [comment]
Looks like the issue was solved by switching sorting style. Closing it.

Please reopen if issue continues.

**Comment by wbhob** [comment]
I am still unable to set this properly. I set this: 
```
  "importSort": {
    ".ts": {
      "parser": "typescript",
      "style": "import-sort-style-module"
    }
  }
```
with no changes. More importantly, this should be a _global_ option. I don't want to set this for each of my dozens of projects.

**Comment by amatiasq** [comment]
This is weird, I'm using the typescript parser in a project and I can see it working now. Are you using react? if you have some `.tsx` files this configuration won't work.

About the global option, it's the reason why I made this fork but I had to rollback when the original plugin was deprecated. You can follow the discussion in #5

**Comment by wbhob** [comment]
How do I set it exactly? The docs are vague about the exact string I have to use.

**Comment by wbhob** [comment]
Also, I’m not using react, just regular old .ts files

**Comment by amatiasq** [comment]
I haven't got deep into the library's implementation. I took the one from that docs and it works.

**Comment by wbhob** [comment]
If I copy from the docs, it still uses the same ESLint style. I need the `module` sort type, which I can not find.

**Comment by amatiasq** [comment]
Oh now I see, may it be that `"style": "import-sort-style-module"` is not expected to get the whole module name, you can skip the `import-sort-style-` part. Maybe that's your issue.
