### ISSUE TITLE
MAINTAINER REQUIRED

### ISSUE THREAD

**Issue by amatiasq** [amatiasq/vsc-sort-imports#41]
I'm sorry to say since I moved to a new job position and personal issues I can't dedicate to this tool the time it deserves and I can't leave the issues unmanaged.

If anyone is interested in taking this ship started by @peterjuras let me know.

I still love and use this tool, I just can't find time for it.

**Comment by jquense** [comment]
@amatiasq I'd be willing to take over. I also have a lot going on so i'm not likely to be the most active maintainer, but i'd be happy move through some of the backlog at least, and keep it up to date since `import-sort` is a big part of our teams workflow

**Comment by amatiasq** [comment]
That's awesome, I can help with the knowledge I earned from this project but I don't have the time to do the debugging myself.

Can I help you get started?

**Comment by amatiasq** [comment]
Thank you @jquense for taking the lead, I'll still be around to do what I can.
