### ISSUE TITLE
TypeError: Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by Matt-Hill-83** [amatiasq/vsc-sort-imports#44]
I get this error when I try to run it with the latest version of VSC.
Any idea how to troubleshoot?

Error sorting imports: TypeError: Cannot read property 'file' of undefined

**Comment by amatiasq** [comment]
Is this still happening? I don't know how to reproduce it

**Comment by Matt-Hill-83** [comment]
Thanks for the response. Nope. It went away. It was something dumb.
