### ISSUE TITLE
`sort-imports` v6.0.2 doesn't work for me.

### ISSUE THREAD

**Issue by thisissami** [amatiasq/vsc-sort-imports#50]
Hi All - `sort-imports` v6.0.2 is broken. Any time I try to sort things, nothing happens. When I use `autosave`, there's no feedback of any kind. When i explicitly run the `Sort imports` command, I get an error message saying 

> Running the contributed command: 'sort-imports.sort' failed. 

from VSCode. 

Does anybody have any idea what might be going on? I've tried uninstalling / reinstalling, removing all my custom settings from `package.json`, and none of this has worked. Reverting to v6.0.1 makes things work.

**Comment by jquense** [comment]
i've got it working for me so it may be specific to your setup. are you using another set of presets? Are they compatible with import-sort v6?

**Comment by thisissami** [comment]
i disabled all my presets and `v6.0.2` still wasn't working. they work just fine with `v6.0.1`, which i assume is still `import-sort v6`. i went to a completely clean install, and it wasn't working at all. also updated VS Code to the latest stable build. I'm using Linux (Pop OS 18.04, which is essentially Ubuntu 18.04), for what that is worth.

**Comment by amatiasq** [comment]
Can't reproduce on MacOS :\

**Comment by thisissami** [comment]
This is fixed with `6.1.0`. however, there's a new bug that i will create a new issue for shortly.
