### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by nasraldin** [amatiasq/vsc-sort-imports#59]
- Issue Type: `Performance`
- Extension Name: `sort-imports`
- Extension Version: `6.1.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.38.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\userprofile\amatiasq.sort-imports-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by amatiasq** [comment]
Is this still happening?

**Comment by nasraldin** [comment]
I am not sure about this, maybe work fine now. thank you for your concern.
