### ISSUE TITLE
This extension prevents tslint autoFixOnSave from working

### ISSUE THREAD

**Issue by chrismcleod** [amatiasq/vsc-sort-imports#6]
to reproduce, install this extension and [vscode-tslint](https://github.com/Microsoft/vscode-tslint)

In settings enable sort imports on save for this extension and auto fix on save for tslint.  TSlint will no longer auto fix on save.

**Comment by chrismcleod** [comment]
This is actually an issue with the tslint extension: https://github.com/Microsoft/vscode-tslint/issues/136

**Comment by amatiasq** [comment]
Thanks for reporting it also here! It's good for people who have the same issue 👍
