### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by himanshu-saxena-hitachi** [amatiasq/vsc-sort-imports#66]
- Issue Type: `Bug`
- Extension Name: `sort-imports`
- Extension Version: `6.1.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.44.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
https://github.com/amatiasq/vsc-sort-imports/issues/new/?body=- Issue Type: `Bug`
- Extension Name: `sort-imports`
- Extension Version: `6.1.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.44.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:&title=Extension issue

**Comment by amatiasq** [comment]
And what's the issue?

**Comment by jerome-benoit** [comment]
No description provided, closing.
