### ISSUE TITLE
ignore file via eslint-like comment

### ISSUE THREAD

**Issue by hbnrmx** [amatiasq/vsc-sort-imports#70]
Hi all!

it would be cool to have the ability to disable the formatting via a comment in the file e.g.
```
//disable sort-imports
```
I made [a fork with this change](https://github.com/hbnrmx/vsc-sort-imports/blob/cc1165373bfc02163e7125857632bf61ccc6b659/src/sort.ts#L30) for our personal use.

Any chance something like this would be merged? :)

Thanks!

**Comment by jquense** [comment]
this should already be supported in import-sort via a `// import-sort-ignore` comment

**Comment by hbnrmx** [comment]
Oh, guess I missed that. Thanks a bunch!
