### ISSUE TITLE
Support import-sort v4

### ISSUE THREAD

**Issue by OliverJAsh** [amatiasq/vsc-sort-imports#8]
What we do we need to do to add support for import-sort v4 which was recently released?

**Comment by amatiasq** [comment]
Not sure, my plan was to check changelog, update it and see if everything is ok.

**Comment by fsmaia** [comment]
As we are finished, I'll be able to advance in development of [module style with relative aliases](https://github.com/fsmaia/import-sort-style-module-relative-aliases), due to support of new `custom` settings attribute. Let me know if I can help with something.

**Comment by OliverJAsh** [comment]
Last time I checked the change log hadn't been updated since v2.

**Comment by amatiasq** [comment]
#10 will fix this

@OliverJAsh That was my plan, I would probably improvise then ;)

**Comment by cliffkoh** [comment]
#10 is merged so I will close this :)
