### ISSUE TITLE
6.2.5: Cannot find module 'import-sort-style-eslint'

### ISSUE THREAD

**Issue by OliverJAsh** [amatiasq/vsc-sort-imports#84]
I just upgraded from 6.2.4 to 6.2.5 and the extension no longer works. In the extension output I see this error:

```
Cannot find module 'import-sort-style-eslint'
```

**Comment by jerome-benoit** [comment]
That issue is not reproducible with various local test setups since https://github.com/amatiasq/vsc-sort-imports/pull/83 merge.

You have to give us a repository where you have the issue 100% of the time to allow more investigation.

Thanks.

**Comment by OliverJAsh** [comment]
@jerome-benoit Here you go: https://github.com/OliverJAsh/vsc-sort-imports-bug

**Comment by secondfry** [comment]
Set your `defaultSortStyle` in extension settings.

**Comment by secondfry** [comment]
So it seems there is a problem with `package.json`, extension settings and caching (as I mentioned in https://github.com/amatiasq/vsc-sort-imports/issues/82#issuecomment-820503979).

If I change extension settings they get picked up immediatelly. If I change `package.json` settings they are not recognized at all.

**Comment by secondfry** [comment]
And also reverting #83 resulted in `import-sort-style-eslint` successfully getting resolved (from bundled `node_modules` I guess).
But then it won't resolve local projects modules.
