### ISSUE TITLE
Cannot find module 'import-sort-style-eslint'

### ISSUE THREAD

**Issue by G21LXDR** [amatiasq/vsc-sort-imports#87]
As soon as I launch **vscode**, in the exit of `sort-imports` it is written this:

![image](https://user-images.githubusercontent.com/81637143/115151726-7255bb80-a06e-11eb-8578-8d2acf3ed004.png)

I tried to reinstall the extension, and even install the modules myself from the root of the extension, but it still does not work.

Any ideas ?

**Comment by G21LXDR** [comment]
Duplicate of #86

**Comment by jerome-benoit** [comment]
Fixed in 6.2.6 version.
