### ISSUE TITLE
Wrong order

### ISSUE THREAD

**Issue by Disorrder** [amatiasq/vsc-sort-imports#92]
![image](https://user-images.githubusercontent.com/2883539/123956200-16cf7480-d9b3-11eb-9d1b-559dff3fb201.png)

libraries from npm should go before local files.
If name starts with `@/` it can be local file, but `@*/*` is not local.
It also should to recognize webpack aliases. For example, I can define `Public/*` as local folder instead of writing `../../../../public/*`

**Comment by amatiasq** [comment]
You can use [one of the multiple sort style provided](https://github.com/amatiasq/vsc-sort-imports#use-a-different-style-or-parser) or create your own sort style if none matches your needs ([example](https://github.com/amatiasq/import-sort-style-module-compact))
